[build]
  publish = "."    
  command = ""

[functions]
  directory = "netlify/functions"
  
# SADECE /pmas kuralı kalıyor.
# Bu, 'pmas.js' fonksiyonunu tetikler.
[[redirects]]
  from = "/pmas"
  to = "/.netlify/functions/pmas"
  status = 200
  force = true

# Ana dizin ("/") kuralı kaldırıldı.