# netlify.toml
[build]
  publish = "public"
  command = ""

[[headers]]
  for = "/pmas.ps1"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    X-Content-Type-Options = "nosniff"
